version: "3"
services:
  backend:
    container_name: backend
    image: arjunkhade/akcode:backend
    restart: always
    ports:
      - 9090:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image:  arjunkhade/akcode:database
    environment:
      MYSQL_DATABASE: fresh_cart
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
  front:
    container_name: front
    image: arjunkhade/akcode:f
    ports:
      - 80:80
