version: "3"
services:
  fresh-cart-backend:
    container_name: fresh-cart-backend
    image: arjunkhade/akcode:fresh-cart-backend
    restart: always
    ports:
      - 9090:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image:  arjunkhade/akcode:fresh_cart_database
    environment:
      MYSQL_DATABASE: fresh_cart
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
  fresh-cart-frontend:
    container_name: fresh_cart_frontend
    image: arjunkhade/akcode:fresh_cart_frontend
    ports:
      - 80:80
